import localFont from "next/font/local";
import "./globals.css";
import { Inter } from 'next/font/google'
import Linki from "@/components/linki";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  subsets: ['latin']

})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <Linki/>
        {children}
      </body>
    </html>
  );
}